import Handsontable from 'handsontable-pro'
var _dictionary

function _defineProperty (obj, key, value) {
  if (key in obj) {
    Object.defineProperty(obj, key, {
      value: value,
      enumerable: true,
      configurable: true,
      writable: true
    })
  } else {
    obj[key] = value
  }
  return obj
};
var C = Handsontable.languages.dictionaryKeys
var dictionary = ((_dictionary = {languageCode: 'en-US'}),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ROW_ABOVE, '在上面插入一行'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ROW_BELOW, '在下面插入一行'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_INSERT_LEFT, '向左插入列'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_INSERT_RIGHT, '向右插入列'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_REMOVE_ROW, ['删除行', '删除多行']),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_REMOVE_COLUMN, ['删除列', '删除多行']),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_UNDO, '复原'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_REDO, '重做'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_READ_ONLY, '只读'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_CLEAR_COLUMN, '清空列'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT, '对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT_LEFT, '左对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT_CENTER, '水平居中对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT_RIGHT, '右对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT_JUSTIFY, '两端对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT_TOP, '顶部对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT_MIDDLE, '垂直居中对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ALIGNMENT_BOTTOM, '底部对齐'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_FREEZE_COLUMN, '冻结列'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_UNFREEZE_COLUMN, '取消冻结列'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_BORDERS, '边界'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_BORDERS_TOP, '顶部'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_BORDERS_RIGHT, '右侧'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_BORDERS_BOTTOM, '底部'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_BORDERS_LEFT, '左侧'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_REMOVE_BORDERS, '删除边框(多个)'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_ADD_COMMENT, '添加评论'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_EDIT_COMMENT, '编辑评论'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_REMOVE_COMMENT, '删除评论'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_READ_ONLY_COMMENT, '只读评论'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_MERGE_CELLS, '合并单元格'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_UNMERGE_CELLS, '取消合并单元格'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_COPY, '复制'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_CUT, '剪切'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_NESTED_ROWS_INSERT_CHILD, '插入子行'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_NESTED_ROWS_DETACH_CHILD, '分离行'),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_HIDE_COLUMN, ['隐藏列', '隐藏多列']),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_SHOW_COLUMN, ['显示列', '显示多列']),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_HIDE_ROW, ['隐藏行', '隐藏多行']),
  _defineProperty(_dictionary, C.CONTEXTMENU_ITEMS_SHOW_ROW, ['显示行', '显示多行']),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_NONE, '无'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_EMPTY, '空'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_NOT_EMPTY, '非空'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_EQUAL, '等于'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_NOT_EQUAL, '不等于'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_BEGINS_WITH, '开头以'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_ENDS_WITH, '结束以'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_CONTAINS, '包含'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_NOT_CONTAIN, '不包含'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_GREATER_THAN, '大于'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_GREATER_THAN_OR_EQUAL, '大于等于'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_LESS_THAN, '小于'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_LESS_THAN_OR_EQUAL, '小于等于'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_BETWEEN, '之间'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_NOT_BETWEEN, '非之间'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_AFTER, '之后'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_BEFORE, '之前'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_TODAY, '今天'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_TOMORROW, '明天'),
  _defineProperty(_dictionary, C.FILTERS_CONDITIONS_YESTERDAY, '昨天'),
  _defineProperty(_dictionary, C.FILTERS_VALUES_BLANK_CELLS, '空白'),
  _defineProperty(_dictionary, C.FILTERS_DIVS_FILTER_BY_CONDITION, '过滤条件'),
  _defineProperty(_dictionary, C.FILTERS_DIVS_FILTER_BY_VALUE, '搜索值'),
  _defineProperty(_dictionary, C.FILTERS_LABELS_CONJUNCTION, '与'),
  _defineProperty(_dictionary, C.FILTERS_LABELS_DISJUNCTION, '或'),
  _defineProperty(_dictionary, C.FILTERS_BUTTONS_SELECT_ALL, '选择所有'),
  _defineProperty(_dictionary, C.FILTERS_BUTTONS_CLEAR, '清除所有'),
  _defineProperty(_dictionary, C.FILTERS_BUTTONS_OK, '确认'),
  _defineProperty(_dictionary, C.FILTERS_BUTTONS_CANCEL, '取消'),
  _defineProperty(_dictionary, C.FILTERS_BUTTONS_PLACEHOLDER_SEARCH, '搜索'),
  _defineProperty(_dictionary, C.FILTERS_BUTTONS_PLACEHOLDER_VALUE, '起始值'),
  _defineProperty(_dictionary, C.FILTERS_BUTTONS_PLACEHOLDER_SECOND_VALUE, '末值'),
  _dictionary)
Handsontable.languages.registerLanguageDictionary(dictionary)
