const userApi = require('./api/userApi')
const fs = require('fs')
const path = require('path')
const bodyParser = require('body-parser')
const express = require('express')
const app = express()
require('./weChat') // websocket
app.use(bodyParser.json())
app.use(bodyParser.urlencoded())
app.use('/api', userApi)
app.listen(3000)